### ISSUE TITLE
business hours 

### ISSUE THREAD

**Issue by kshitijmishra23** [trotzig/react-available-times#4]
Is there a way by which we can add business hours(slots selection restricted ) to the calendar. Or can we highlight some time slots in a different color ?

**Comment by trotzig** [comment]
Right now I don't think there's anything supporting this use-case. You might be able to hack together something using the `calendars` and `onEventsRequested` props, but it wouldn't restrict selections unfortunately. 

I'd be happy to review a PR adding support for this though. You could add a `businessHours` prop to `<AvailableTimes>`, then feeding that down through `<Week>` and finally down to `<Day>`. The Day component can then add some kind of overlay element for when the day is outside of business hours (semi-transparent to indicate it's "dead"). You would also have to adjust the restriction of selections. 

Let me know if you need to bounce around ideas for this.

**Comment by causztic** [comment]
@trotzig I just forked the repo with this intention, and also ideally adding businessDays restriction as well.

**Comment by trotzig** [comment]
Lovely! Like I said, don't be afraid to reach out if you need help.

**Comment by causztic** [comment]
<img width="1439" alt="screen shot 2018-03-14 at 9 34 05 am" src="https://user-images.githubusercontent.com/2081441/37378626-eddbfa24-276a-11e8-8403-2680137a42f8.png">
I have just added the availableDays functionality, basically passing an array of `availableDays` down to `Day`, `DayHeader` and `Week`, graying out and disabling events as required.

Now for availableHours..
